fps
frametime
frame_timing
cpu_stats
cpu_temp
gpu_stats
gpu_temp
vram
ram
gpu_load_change
cpu_load_change
gpu_color=2E9762
cpu_color=2E97CB
background_alpha=0.4
font_size=20
position=top-left
toggle_hud=Shift_R+F12
